# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mohamedelleuch/Programming/gnu_c_cpp/carthage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mohamedelleuch/Programming/gnu_c_cpp/carthage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mohamedelleuch/Programming/gnu_c_cpp/carthage/CMakeFiles /Users/mohamedelleuch/Programming/gnu_c_cpp/carthage//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mohamedelleuch/Programming/gnu_c_cpp/carthage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named carthage-code-gen

# Build rule for target.
carthage-code-gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 carthage-code-gen
.PHONY : carthage-code-gen

# fast build rule for target.
carthage-code-gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-code-gen.dir/build.make CMakeFiles/carthage-code-gen.dir/build
.PHONY : carthage-code-gen/fast

#=============================================================================
# Target rules for targets named carthage-parse

# Build rule for target.
carthage-parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 carthage-parse
.PHONY : carthage-parse

# fast build rule for target.
carthage-parse/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-parse.dir/build.make CMakeFiles/carthage-parse.dir/build
.PHONY : carthage-parse/fast

#=============================================================================
# Target rules for targets named carthage-lex

# Build rule for target.
carthage-lex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 carthage-lex
.PHONY : carthage-lex

# fast build rule for target.
carthage-lex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-lex.dir/build.make CMakeFiles/carthage-lex.dir/build
.PHONY : carthage-lex/fast

src/code-gen/main.o: src/code-gen/main.cpp.o
.PHONY : src/code-gen/main.o

# target to build an object file
src/code-gen/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-code-gen.dir/build.make CMakeFiles/carthage-code-gen.dir/src/code-gen/main.cpp.o
.PHONY : src/code-gen/main.cpp.o

src/code-gen/main.i: src/code-gen/main.cpp.i
.PHONY : src/code-gen/main.i

# target to preprocess a source file
src/code-gen/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-code-gen.dir/build.make CMakeFiles/carthage-code-gen.dir/src/code-gen/main.cpp.i
.PHONY : src/code-gen/main.cpp.i

src/code-gen/main.s: src/code-gen/main.cpp.s
.PHONY : src/code-gen/main.s

# target to generate assembly for a file
src/code-gen/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-code-gen.dir/build.make CMakeFiles/carthage-code-gen.dir/src/code-gen/main.cpp.s
.PHONY : src/code-gen/main.cpp.s

src/lexer/main.o: src/lexer/main.cpp.o
.PHONY : src/lexer/main.o

# target to build an object file
src/lexer/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-lex.dir/build.make CMakeFiles/carthage-lex.dir/src/lexer/main.cpp.o
.PHONY : src/lexer/main.cpp.o

src/lexer/main.i: src/lexer/main.cpp.i
.PHONY : src/lexer/main.i

# target to preprocess a source file
src/lexer/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-lex.dir/build.make CMakeFiles/carthage-lex.dir/src/lexer/main.cpp.i
.PHONY : src/lexer/main.cpp.i

src/lexer/main.s: src/lexer/main.cpp.s
.PHONY : src/lexer/main.s

# target to generate assembly for a file
src/lexer/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-lex.dir/build.make CMakeFiles/carthage-lex.dir/src/lexer/main.cpp.s
.PHONY : src/lexer/main.cpp.s

src/parser/main.o: src/parser/main.cpp.o
.PHONY : src/parser/main.o

# target to build an object file
src/parser/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-parse.dir/build.make CMakeFiles/carthage-parse.dir/src/parser/main.cpp.o
.PHONY : src/parser/main.cpp.o

src/parser/main.i: src/parser/main.cpp.i
.PHONY : src/parser/main.i

# target to preprocess a source file
src/parser/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-parse.dir/build.make CMakeFiles/carthage-parse.dir/src/parser/main.cpp.i
.PHONY : src/parser/main.cpp.i

src/parser/main.s: src/parser/main.cpp.s
.PHONY : src/parser/main.s

# target to generate assembly for a file
src/parser/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/carthage-parse.dir/build.make CMakeFiles/carthage-parse.dir/src/parser/main.cpp.s
.PHONY : src/parser/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... carthage-code-gen"
	@echo "... carthage-lex"
	@echo "... carthage-parse"
	@echo "... src/code-gen/main.o"
	@echo "... src/code-gen/main.i"
	@echo "... src/code-gen/main.s"
	@echo "... src/lexer/main.o"
	@echo "... src/lexer/main.i"
	@echo "... src/lexer/main.s"
	@echo "... src/parser/main.o"
	@echo "... src/parser/main.i"
	@echo "... src/parser/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

